// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PA_PaletaVegetal.Server.Data;

#nullable disable

namespace PA_PaletaVegetal.Server.Migrations
{
    [DbContext(typeof(PA_PaletaVegetalServerContext))]
    [Migration("20260331195224_AgregarMedidasVegetacion")]
    partial class AgregarMedidasVegetacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PA_PaletaVegetal.Server.Models.Vegetacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<int>("Asoleamiento")
                        .HasColumnType("int");

                    b.Property<double>("Copa")
                        .HasColumnType("float");

                    b.Property<int>("Crecimiento")
                        .HasColumnType("int");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Raiz")
                        .HasColumnType("int");

                    b.Property<int>("Riego")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<double>("Tronco")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Vegetacion");
                });
#pragma warning restore 612, 618
        }
    }
}
