// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PA_PaletaVegetal.Server.Data;

#nullable disable

namespace PA_PaletaVegetal.Server.Migrations
{
    [DbContext(typeof(PA_PaletaVegetalServerContext))]
    partial class PA_PaletaVegetalServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PA_PaletaVegetal.Server.Models.Vegetacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AlturaMax")
                        .HasColumnType("float");

                    b.Property<double>("AlturaMin")
                        .HasColumnType("float");

                    b.Property<int>("Asoleamiento")
                        .HasColumnType("int");

                    b.Property<double>("CopaMax")
                        .HasColumnType("float");

                    b.Property<double>("CopaMin")
                        .HasColumnType("float");

                    b.Property<int>("Crecimiento")
                        .HasColumnType("int");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Raiz")
                        .HasColumnType("int");

                    b.Property<int>("Riego")
                        .HasColumnType("int");

                    b.Property<string>("TablaCromaticaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<double>("TroncoMax")
                        .HasColumnType("float");

                    b.Property<double>("TroncoMin")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Vegetacion");
                });
#pragma warning restore 612, 618
        }
    }
}
